export const root: string;
export const visitingCard: string;
export const popLayer: string;
export const showPop: string;
export const popContent: string;
export const closePop: string;
export const popMyMood: string;
export const finishBtn: string;
export const popUpload: string;
