export const root: string;
export const rootFixed: string;
export const inform: string;
export const nickName: string;
export const icon: string;
export const credit: string;
export const funcEntry: string;
export const receiveMsg: string;
export const btns: string;
